using System.Globalization;
using System.Security.Cryptography;
using System.Text;

namespace Charter.Storage;

/// <summary>
/// Builds and validates object keys from components Charter did not write (section 16).
/// </summary>
/// <remarks>
/// <para>
/// Every component that ends up in a key comes from somewhere untrusted: a check name out of a
/// repository's <c>.charter/config.yml</c>, a file path out of an agent's tool call, a property name
/// out of an adapter's JSON. A check named <c>../../../etc/passwd</c> is a realistic input, not a
/// theoretical one - the repository is written by whoever opened the pull request, and the agent's
/// output is model-authored text.
/// </para>
/// <para>
/// So no untrusted string is ever concatenated into a path. It is reduced to
/// <c>[A-Za-z0-9._-]</c>, stripped of leading and trailing dots, capped in length, and replaced
/// wholesale when what is left is empty or is a relative-path token. The result cannot contain a
/// separator, so it cannot introduce a segment; and because the session id is generated by Charter
/// and formatted rather than passed through, the prefix a key lands under is never influenced by the
/// components under it.
/// </para>
/// <para>
/// <see cref="IsWithinSession"/> is the other half, and it is what the read endpoint asks. A key
/// arriving from a URL is checked against the session the caller was authorised for, so a path that
/// somehow escaped sanitisation still cannot address another session's bytes.
/// </para>
/// </remarks>
public static class ObjectKey
{
    /// <summary>The prefix every session's objects live under.</summary>
    public const string SessionPrefix = "sessions";

    /// <summary>The longest a single sanitised component may be.</summary>
    public const int MaxSegmentLength = 64;

    /// <summary>The longest a whole key may be, so no backend refuses one Charter built.</summary>
    public const int MaxKeyLength = 512;

    /// <summary>What a component that sanitises away is called instead.</summary>
    public const string Fallback = "unnamed";

    /// <summary>
    /// One untrusted string, reduced to something that can only ever be a single path component.
    /// </summary>
    public static string Segment(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return Fallback;
        }

        var builder = new StringBuilder(Math.Min(value.Length, MaxSegmentLength));
        var lastWasSeparator = false;

        foreach (var character in value.Trim())
        {
            if (builder.Length >= MaxSegmentLength)
            {
                break;
            }

            if (char.IsAsciiLetterOrDigit(character))
            {
                builder.Append(character);
                lastWasSeparator = false;
                continue;
            }

            // '.' is deliberately not in this set. Keeping it would mean handling '..' as a special
            // case afterwards, and a rule with an exception is a rule somebody eventually gets wrong;
            // dropping it entirely costs nothing but a dot in a check name.
            if (character is '-' or '_' or '.' or ' ' or '/' or '\\')
            {
                if (!lastWasSeparator && builder.Length > 0)
                {
                    builder.Append('-');
                    lastWasSeparator = true;
                }

                continue;
            }

            if (!lastWasSeparator && builder.Length > 0)
            {
                builder.Append('-');
                lastWasSeparator = true;
            }
        }

        var segment = builder.ToString().Trim('-');

        return segment.Length == 0 ? Fallback : segment;
    }

    /// <summary>
    /// A key under one session's prefix, from components that may be anything at all.
    /// </summary>
    /// <param name="sessionId">Charter's own identifier. Formatted, never passed through.</param>
    /// <param name="segments">Untrusted components, in order. Each becomes exactly one segment.</param>
    public static string ForSession(Guid sessionId, params string?[] segments)
    {
        ArgumentNullException.ThrowIfNull(segments);

        var parts = new List<string>(segments.Length + 2)
        {
            SessionPrefix,
            sessionId.ToString("N", CultureInfo.InvariantCulture),
        };

        parts.AddRange(segments.Select(Segment));

        var key = string.Join('/', parts);

        return key.Length <= MaxKeyLength ? key : Shorten(key);
    }

    /// <summary>
    /// The same key with a file extension, which decides how the read endpoint serves it.
    /// </summary>
    /// <remarks>
    /// Appended after sanitisation rather than passed through it, because <see cref="Segment"/>
    /// deliberately turns a dot into a separator - so an extension inside an untrusted component
    /// cannot survive, and an extension Charter itself chose has to be added afterwards. The
    /// extension is checked here rather than trusted: it comes from Charter, and a rule that only
    /// holds while every caller behaves is not a rule.
    /// </remarks>
    public static string WithExtension(string key, string extension)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(key);
        ArgumentException.ThrowIfNullOrWhiteSpace(extension);

        if (!extension.All(char.IsAsciiLetterOrDigit))
        {
            throw new ArgumentException($"'{extension}' is not a usable file extension.", nameof(extension));
        }

        return key + "." + extension;
    }

    /// <summary>The prefix every object of one session sits under, with its trailing slash.</summary>
    public static string SessionScope(Guid sessionId)
        => string.Create(CultureInfo.InvariantCulture, $"{SessionPrefix}/{sessionId:N}/");

    /// <summary>
    /// True when <paramref name="key"/> is a well-formed key inside <paramref name="sessionId"/>'s prefix.
    /// </summary>
    /// <remarks>
    /// Rejects, in order: an empty key, a rooted or drive-qualified one, any segment that is empty
    /// or a relative-path token, any character outside the sanitised alphabet, and finally anything
    /// not under this session. The last check alone would be enough to stop cross-session reads; the
    /// ones before it stop a key that would mean something different to a filesystem than to a bucket.
    /// </remarks>
    public static bool IsWithinSession(string? key, Guid sessionId)
    {
        if (string.IsNullOrWhiteSpace(key) || key.Length > MaxKeyLength)
        {
            return false;
        }

        if (key.StartsWith('/') || key.StartsWith('\\') || key.Contains('\\', StringComparison.Ordinal))
        {
            return false;
        }

        var segments = key.Split('/');

        foreach (var segment in segments)
        {
            if (segment.Length == 0 || segment is "." or "..")
            {
                return false;
            }

            foreach (var character in segment)
            {
                if (!char.IsAsciiLetterOrDigit(character) && character is not ('-' or '_' or '.'))
                {
                    return false;
                }
            }
        }

        return segments.Length > 2
               && string.Equals(segments[0], SessionPrefix, StringComparison.Ordinal)
               && string.Equals(segments[1], sessionId.ToString("N", CultureInfo.InvariantCulture), StringComparison.Ordinal);
    }

    /// <summary>The last segment of a key - what a download is named.</summary>
    public static string FileName(string key)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(key);

        var slash = key.LastIndexOf('/');
        return slash >= 0 && slash < key.Length - 1 ? key[(slash + 1)..] : key;
    }

    /// <summary>A short, stable, collision-resistant token for an arbitrary string.</summary>
    /// <remarks>
    /// Used where a key needs to be a pure function of something unbounded - an event's idempotency
    /// key, most often. Deterministic on purpose: a redelivered event has to overwrite its own object
    /// rather than accumulate a second copy of it.
    /// </remarks>
    public static string Token(string value)
    {
        ArgumentNullException.ThrowIfNull(value);

        var hash = SHA256.HashData(Encoding.UTF8.GetBytes(value));
        return Convert.ToHexStringLower(hash)[..16];
    }

    private static string Shorten(string key)
    {
        // Keep the front, which is what a human reads, and end with a token of the whole thing so two
        // long keys that shared a prefix cannot collapse into one object.
        var token = Token(key);
        return string.Concat(key.AsSpan(0, MaxKeyLength - token.Length - 1), "-", token);
    }
}
