using System.Text;
using Charter.VersionControl;

namespace Charter.Runners.Shim;

/// <summary>Who a commit Charter generates is attributed to.</summary>
/// <remarks>
/// <para>
/// The requester, by name and address — the person who asked for the change. Section 7.3 requires
/// every agent action to be attributable to a named human, and the commit is the most durable place
/// that attribution can live: it outlives the session, the change request and Charter itself.
/// </para>
/// <para>
/// Nothing about the tooling appears here, and section 24 is why. Nothing in a repository's history
/// may suggest a change was written by a tool rather than by a person, and that rule governs the
/// commits Charter generates exactly as it governs the ones a maintainer types. That Charter produced
/// the commit is recorded where it belongs — on the change request, which says so in words.
/// </para>
/// </remarks>
public sealed record ShimCommitIdentity
{
    private ShimCommitIdentity(string name, string email)
    {
        Name = name;
        Email = email;
    }

    public string Name { get; }

    public string Email { get; }

    /// <summary>The <c>Name &lt;address&gt;</c> form git wants.</summary>
    public string Format() => $"{Name} <{Email}>";

    /// <summary>
    /// Builds an identity, or answers null when there is not a usable one.
    /// </summary>
    /// <remarks>
    /// A name carrying angle brackets or a newline would let a dispatch payload forge extra headers
    /// into the commit object, so those characters are removed rather than escaped. An identity that
    /// does not survive that is no identity, and the caller falls back to the repository's own git
    /// configuration instead of committing as something invented here.
    /// </remarks>
    public static ShimCommitIdentity? TryCreate(string? name, string? email)
    {
        var cleanName = Clean(name);
        var cleanEmail = Clean(email);

        return cleanName.Length > 0 && cleanEmail.Contains('@', StringComparison.Ordinal)
            ? new ShimCommitIdentity(cleanName, cleanEmail)
            : null;
    }

    private static string Clean(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return string.Empty;
        }

        var builder = new StringBuilder(value.Length);

        foreach (var character in value)
        {
            if (character is '<' or '>' || char.IsControl(character))
            {
                continue;
            }

            builder.Append(character);
        }

        return builder.ToString().Trim();
    }
}

/// <summary>
/// The message of a commit Charter generates.
/// </summary>
/// <remarks>
/// <para>
/// Derived from the approved specification, because that is the description of the change that a
/// human already reviewed (section 16). The specification's title becomes the subject and its opening
/// paragraph the body: the message describes the change and nothing else.
/// </para>
/// <para>
/// Any line that reads as authorship attribution is dropped. The specification is model-authored, so
/// a phrase like <c>Co-authored-by</c> or <c>Generated with</c> can arrive in it as ordinary prose,
/// and section 24's rule is absolute regardless of how the text got there.
/// </para>
/// </remarks>
public static class ShimCommitMessage
{
    /// <summary>The usual limit, and what the change request title is trimmed to as well.</summary>
    public const int MaxSubjectLength = 72;

    /// <summary>What the subject falls back to when the specification carries no title.</summary>
    public const string FallbackSubject = "Apply the approved specification";

    private const int WrapColumn = 72;

    private static readonly string[] AttributionMarkers =
    [
        "co-authored-by",
        "co-authored by",
        "generated with",
        "generated by",
        "authored by",
        "written by",
        "created by",
        "assisted-by",
        "assisted by",
        "🤖",
    ];

    /// <summary>Builds the message for one session's commit from the approved specification.</summary>
    public static string Build(string? specMarkdown)
    {
        var lines = (specMarkdown ?? string.Empty)
            .Replace("\r\n", "\n", StringComparison.Ordinal)
            .Split('\n');

        var subject = Subject(lines);
        var body = Body(lines);

        return body.Length == 0 ? subject : $"{subject}\n\n{body}";
    }

    /// <summary>True when a line reads as a byline rather than as a description of the change.</summary>
    public static bool LooksLikeAttribution(string line)
    {
        ArgumentNullException.ThrowIfNull(line);

        foreach (var marker in AttributionMarkers)
        {
            if (line.Contains(marker, StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return false;
    }

    private static string Subject(IReadOnlyList<string> lines)
    {
        foreach (var line in lines)
        {
            var candidate = line.Trim();

            if (candidate.Length == 0)
            {
                continue;
            }

            if (candidate.StartsWith('#'))
            {
                candidate = candidate.TrimStart('#').Trim();
            }

            candidate = Collapse(candidate).TrimEnd('.');

            if (candidate.Length == 0 || LooksLikeAttribution(candidate))
            {
                continue;
            }

            return Truncate(candidate);
        }

        return FallbackSubject;
    }

    /// <summary>The specification's opening paragraph, wrapped, with the title skipped.</summary>
    private static string Body(IReadOnlyList<string> lines)
    {
        var paragraph = new List<string>();
        var seenSubject = false;

        foreach (var line in lines)
        {
            var candidate = line.Trim();

            if (candidate.Length == 0)
            {
                if (paragraph.Count > 0)
                {
                    break;
                }

                continue;
            }

            if (!seenSubject)
            {
                seenSubject = true;
                continue;
            }

            if (candidate.StartsWith('#') || LooksLikeAttribution(candidate))
            {
                continue;
            }

            paragraph.Add(candidate);
        }

        return paragraph.Count == 0 ? string.Empty : Wrap(Collapse(string.Join(' ', paragraph)));
    }

    private static string Collapse(string value)
        => string.Join(' ', value.Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries));

    private static string Truncate(string value)
    {
        if (value.Length <= MaxSubjectLength)
        {
            return value;
        }

        var clipped = value[..MaxSubjectLength];
        var lastSpace = clipped.LastIndexOf(' ');

        return (lastSpace > MaxSubjectLength / 2 ? clipped[..lastSpace] : clipped).TrimEnd(',', ';', ':', ' ');
    }

    private static string Wrap(string paragraph)
    {
        var builder = new StringBuilder();
        var column = 0;

        foreach (var word in paragraph.Split(' ', StringSplitOptions.RemoveEmptyEntries))
        {
            if (column > 0 && column + 1 + word.Length > WrapColumn)
            {
                builder.Append('\n');
                column = 0;
            }
            else if (column > 0)
            {
                builder.Append(' ');
                column++;
            }

            builder.Append(word);
            column += word.Length;
        }

        return builder.ToString();
    }
}

/// <summary>What one git invocation produced.</summary>
/// <param name="ExitCode">Zero on success.</param>
/// <param name="Output">Standard output, with the lines rejoined exactly as they arrived.</param>
/// <param name="Error">Standard error, when there was any.</param>
public sealed record ShimGitResult(int ExitCode, string Output, string? Error)
{
    public bool Succeeded => ExitCode == 0;

    /// <summary>The first line of standard output, trimmed. A revision, a branch name, a yes.</summary>
    public string FirstLine => Output.Split('\n', StringSplitOptions.RemoveEmptyEntries) is [var first, ..]
        ? first.Trim()
        : string.Empty;

    /// <summary>Splits NUL-delimited output, as <c>-z</c> produces it.</summary>
    public IReadOnlyList<string> NulSeparated =>
    [
        .. Output
            .Split('\0', StringSplitOptions.RemoveEmptyEntries)
            .Select(entry => entry.Trim('\n', '\r'))
            .Where(entry => entry.Length > 0),
    ];
}

/// <summary>Runs git inside the session workspace, through the shim's one process seam.</summary>
/// <remarks>
/// Every invocation carries the same three <c>-c</c> settings, and each closes a way a session could
/// fail or hang on a host's configuration rather than on its own work: <c>safe.directory</c> because
/// a checkout owned by a different uid inside a container is otherwise refused outright,
/// <c>commit.gpgsign=false</c> because an operator's global signing configuration would block a
/// commit no key is present for, and <c>GIT_TERMINAL_PROMPT=0</c> because a push with no usable
/// credential must fail in seconds with a message rather than block on a prompt nobody can answer.
/// </remarks>
public sealed class ShimGit
{
    private readonly IShimProcessRunner _processes;
    private readonly string _workspace;

    public ShimGit(IShimProcessRunner processes, string workspace)
    {
        ArgumentNullException.ThrowIfNull(processes);
        ArgumentException.ThrowIfNullOrWhiteSpace(workspace);

        _processes = processes;
        _workspace = Path.GetFullPath(workspace);
    }

    public async Task<ShimGitResult> RunAsync(
        IReadOnlyList<string> arguments,
        string? standardInput = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(arguments);

        var output = new List<string>();

        var result = await _processes.RunAsync(
            new ShimProcessRequest(
                "git",
                [
                    "-C", _workspace,
                    "-c", $"safe.directory={_workspace}",
                    "-c", "commit.gpgsign=false",
                    .. arguments,
                ],
                _workspace,
                standardInput,
                new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["GIT_TERMINAL_PROMPT"] = "0",
                }),
            (line, _) =>
            {
                output.Add(line);
                return ValueTask.CompletedTask;
            },
            cancellationToken);

        return new ShimGitResult(result.ExitCode, string.Join('\n', output), result.Error);
    }
}

/// <summary>
/// Makes sure the session has a checkout to work in.
/// </summary>
/// <remarks>
/// <para>
/// Two of the three backends hand the shim a checkout already: the GitHub Actions workflow runs
/// <c>actions/checkout</c> at the base commit, and the Charter Agent clones into the job's scoped
/// working directory. <see cref="DockerRunner"/> has neither — its container starts empty — so the
/// shim clones for itself when, and only when, the workspace is not already a work tree. Doing it
/// this way rather than in each backend keeps the checkout in the same place as everything else the
/// sandbox does, and means a backend that already cloned is untouched.
/// </para>
/// <para>
/// Where a credential is supplied it goes into the remote URL. That writes it into the container's own
/// <c>.git/config</c>, which is exactly what <c>persist-credentials</c> does on GitHub Actions and is
/// safe for the same reason: the token is short-TTL, scoped to one repository, and the container is
/// destroyed with it (section 7.4).
/// </para>
/// </remarks>
public sealed class ShimCheckout
{
    private readonly IShimProcessRunner _processes;

    public ShimCheckout(IShimProcessRunner processes)
    {
        ArgumentNullException.ThrowIfNull(processes);
        _processes = processes;
    }

    /// <summary>Clones when there is nothing there. Answers null when there was nothing to do.</summary>
    /// <returns>An operator-readable problem, or null on success.</returns>
    public async Task<string?> EnsureAsync(
        string workspaceRoot,
        string? cloneUrl,
        string? baseCommit,
        string? gitToken,
        CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(workspaceRoot);

        Directory.CreateDirectory(workspaceRoot);

        var git = new ShimGit(_processes, workspaceRoot);

        if ((await git.RunAsync(["rev-parse", "--is-inside-work-tree"], null, cancellationToken)).Succeeded)
        {
            return null;
        }

        if (string.IsNullOrWhiteSpace(cloneUrl))
        {
            return $"'{workspaceRoot}' is not a git checkout and the session was dispatched with no "
                + "clone URL, so there is nothing to work on.";
        }

        var cloned = await git.RunAsync(
            ["clone", "--no-single-branch", Authenticate(cloneUrl, gitToken), "."],
            null,
            cancellationToken);

        if (!cloned.Succeeded)
        {
            return $"Charter could not clone the repository into '{workspaceRoot}'. "
                + Redact(Detail(cloned), gitToken);
        }

        if (string.IsNullOrWhiteSpace(baseCommit))
        {
            return null;
        }

        // Detached, at the exact revision the session was planned against. Section 17 computes
        // staleness from that commit, so starting anywhere else makes the comparison meaningless.
        var checkedOut = await git.RunAsync(
            ["checkout", "--detach", baseCommit],
            null,
            cancellationToken);

        return checkedOut.Succeeded
            ? null
            : $"Charter cloned the repository but could not check out '{baseCommit}'. {Detail(checkedOut)}";
    }

    /// <summary>Puts a short-TTL token into an HTTPS remote, in the form GitHub documents.</summary>
    internal static string Authenticate(string cloneUrl, string? token)
    {
        if (string.IsNullOrWhiteSpace(token)
            || !cloneUrl.StartsWith("https://", StringComparison.OrdinalIgnoreCase)
            || cloneUrl.Contains('@', StringComparison.Ordinal))
        {
            return cloneUrl;
        }

        return $"https://x-access-token:{token}@{cloneUrl["https://".Length..]}";
    }

    /// <summary>Keeps a credential out of an error message that will be published as an event.</summary>
    internal static string Redact(string message, string? token)
        => string.IsNullOrWhiteSpace(token)
            ? message
            : message.Replace(token, "***", StringComparison.Ordinal);

    private static string Detail(ShimGitResult result)
    {
        var detail = string.IsNullOrWhiteSpace(result.Error) ? result.Output : result.Error;

        return string.IsNullOrWhiteSpace(detail)
            ? $"git exited with code {result.ExitCode}."
            : detail.Trim().Split('\n')[^1].Trim();
    }
}

/// <summary>How publishing a session's work turned out.</summary>
public enum ShimPublishOutcome
{
    /// <summary>Committed and pushed. The <c>branch_pushed</c> event follows.</summary>
    Published,

    /// <summary>
    /// The agent changed nothing. Section 6's <c>NoChangesNeeded</c>: a real outcome, never a failure,
    /// and never to be confused with a push that did not work.
    /// </summary>
    NoChanges,

    /// <summary>Something staged for commit sits outside the session's path scope (section 7.3).</summary>
    ScopeViolation,

    /// <summary>Git refused. The commit, the push or the workspace itself.</summary>
    Failed,
}

/// <summary>The result of publishing one session's work.</summary>
/// <param name="Outcome">What happened.</param>
/// <param name="Branch">The branch the work landed on, when it landed.</param>
/// <param name="Revision">The commit the branch now points at.</param>
/// <param name="Message">One line, safe to show an engineer.</param>
/// <param name="Paths">The workspace-relative files the commit carries.</param>
/// <param name="Violation">Set when a staged path was outside the scope.</param>
public sealed record ShimPublishResult(
    ShimPublishOutcome Outcome,
    string? Branch,
    string? Revision,
    string Message,
    IReadOnlyList<string> Paths,
    PathScopeDecision? Violation = null);

/// <summary>Everything publishing one session's work needs.</summary>
public sealed record ShimPublishRequest
{
    public required string WorkspaceRoot { get; init; }

    /// <summary>Where the work lands. <see cref="ChangeRequestPublisher.BranchFor"/> by convention.</summary>
    public required string Branch { get; init; }

    public string Remote { get; init; } = "origin";

    /// <summary>
    /// The requester. Null falls back to the checkout's own git configuration rather than to an
    /// identity invented here.
    /// </summary>
    public ShimCommitIdentity? Author { get; init; }

    public required string Message { get; init; }

    /// <summary>False commits without pushing. For a workspace with nowhere to push to.</summary>
    public bool Push { get; init; } = true;
}

/// <summary>
/// Commits and pushes what the agent changed, which is the step that gives
/// <see cref="ChangeRequestPublisher"/> an input (sections 2.2, 6).
/// </summary>
/// <remarks>
/// <para>
/// This runs in the sandbox, after the agent CLI has exited and the checks have been classified,
/// because those are the two things that can still stop the work from being publishable. It is also
/// the second place path scope is enforced, and the more important one: the first checks what the
/// agent <em>said</em> it wrote, and this checks what is actually about to be committed. A write the
/// agent never announced, or announced under a different name, is caught here or not at all — so a
/// staged path outside the scope fails the session loudly rather than riding along in the commit
/// (section 7.3).
/// </para>
/// <para>
/// The three outcomes are kept distinct on purpose. A session that changed nothing is
/// <see cref="ShimPublishOutcome.NoChanges"/> and completes; a push that did not work is
/// <see cref="ShimPublishOutcome.Failed"/> and does not. Collapsing them would make a broken
/// credential look, to the requester, exactly like an agent that decided there was nothing to do.
/// </para>
/// </remarks>
public sealed class ShimPublisher
{
    private readonly ShimGit _git;
    private readonly ShimPathScope _scope;

    public ShimPublisher(IShimProcessRunner processes, ShimPathScope scope)
    {
        ArgumentNullException.ThrowIfNull(processes);
        ArgumentNullException.ThrowIfNull(scope);

        _git = new ShimGit(processes, scope.WorkspaceRoot);
        _scope = scope;
    }

    public async Task<ShimPublishResult> PublishAsync(
        ShimPublishRequest request,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);

        var inside = await _git.RunAsync(["rev-parse", "--is-inside-work-tree"], null, cancellationToken);
        if (!inside.Succeeded)
        {
            return Failed(
                $"'{_scope.WorkspaceRoot}' is not a git checkout, so there is nothing to publish. "
                + Detail(inside));
        }

        // Stage first, then ask the index what is actually there. Asking git rather than trusting the
        // transcript is the point: this is the list that would be committed.
        var staged = await _git.RunAsync(["add", "--all", "--", "."], null, cancellationToken);
        if (!staged.Succeeded)
        {
            return Failed($"Charter could not stage the session's work. {Detail(staged)}");
        }

        var listed = await _git.RunAsync(
            ["diff", "--cached", "--name-only", "-z", "--no-renames"],
            null,
            cancellationToken);

        if (!listed.Succeeded)
        {
            return Failed($"Charter could not read what the session changed. {Detail(listed)}");
        }

        var paths = listed.NulSeparated;

        if (paths.Count == 0)
        {
            return new ShimPublishResult(
                ShimPublishOutcome.NoChanges,
                null,
                null,
                "The agent finished without changing anything, so there is nothing to publish.",
                []);
        }

        // Section 7.3, on what gets committed rather than on what was announced.
        foreach (var path in paths)
        {
            var decision = _scope.Evaluate(path);

            if (!decision.Allowed)
            {
                return new ShimPublishResult(
                    ShimPublishOutcome.ScopeViolation,
                    null,
                    null,
                    decision.Explanation
                    ?? $"'{path}' is outside the path scope this session was dispatched with.",
                    paths,
                    decision);
            }
        }

        var branched = await _git.RunAsync(["checkout", "-B", request.Branch], null, cancellationToken);
        if (!branched.Succeeded)
        {
            return Failed($"Charter could not create the branch '{request.Branch}'. {Detail(branched)}");
        }

        var committed = await _git.RunAsync(
            [
                .. Identity(request.Author),

                "commit",

                // The repository's hooks are repository-controlled code, and the session's gates are
                // the shim's own (sections 7.3, 15, 16). Running an arbitrary hook at commit time
                // would add a code path neither of them covers.
                "--no-verify",

                // Without this git strips every line starting with '#', and a specification's own
                // markdown headings are exactly that.
                "--cleanup=whitespace",
                "--file=-",
                .. Author(request.Author),
            ],
            request.Message,
            cancellationToken);

        if (!committed.Succeeded)
        {
            return Failed($"Charter could not commit the session's work. {Detail(committed)}");
        }

        var revision = await _git.RunAsync(["rev-parse", "HEAD"], null, cancellationToken);
        if (!revision.Succeeded || revision.FirstLine.Length == 0)
        {
            return Failed($"Charter committed the work but could not read the commit back. {Detail(revision)}");
        }

        if (!request.Push)
        {
            return new ShimPublishResult(
                ShimPublishOutcome.Published,
                request.Branch,
                revision.FirstLine,
                $"Committed {paths.Count} file{(paths.Count == 1 ? string.Empty : "s")} on {request.Branch}.",
                paths);
        }

        var pushed = await _git.RunAsync(
            ["push", request.Remote, $"refs/heads/{request.Branch}:refs/heads/{request.Branch}"],
            null,
            cancellationToken);

        if (!pushed.Succeeded)
        {
            return Failed(
                $"Charter committed the session's work but could not push '{request.Branch}' to "
                + $"'{request.Remote}'. {Detail(pushed)}");
        }

        return new ShimPublishResult(
            ShimPublishOutcome.Published,
            request.Branch,
            revision.FirstLine,
            $"Pushed {paths.Count} changed file{(paths.Count == 1 ? string.Empty : "s")} to {request.Branch}.",
            paths);
    }

    /// <summary>The committer, when the dispatch named one. Otherwise the checkout's own.</summary>
    private static IReadOnlyList<string> Identity(ShimCommitIdentity? author) => author is null
        ? []
        : ["-c", $"user.name={author.Name}", "-c", $"user.email={author.Email}"];

    private static IReadOnlyList<string> Author(ShimCommitIdentity? author) => author is null
        ? []
        : [$"--author={author.Format()}"];

    private static ShimPublishResult Failed(string message)
        => new(ShimPublishOutcome.Failed, null, null, message, []);

    private static string Detail(ShimGitResult result)
    {
        var detail = string.IsNullOrWhiteSpace(result.Error) ? result.Output : result.Error;

        return string.IsNullOrWhiteSpace(detail)
            ? $"git exited with code {result.ExitCode}."
            : detail.Trim().Split('\n')[^1].Trim();
    }
}
