// <auto-generated />
using System;
using Charter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Charter.Data.Migrations
{
    [DbContext(typeof(CharterDbContext))]
    [Migration("20260810023234_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Charter.Domain.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("TargetId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("target_type");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_audit_logs_actor_user_id");

                    b.HasIndex("OrgId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_logs_org_id_created_at");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("ix_audit_logs_target_type_target_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Charter.Domain.AutoDispatchPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("AllowedPaths")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("allowed_paths");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int?>("MaxConcurrentSessions")
                        .HasColumnType("integer")
                        .HasColumnName("max_concurrent_sessions");

                    b.Property<decimal?>("MaxCostUsd")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("max_cost_usd");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.PrimitiveCollection<string[]>("ProjectTypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("project_types");

                    b.Property<Guid?>("RepoId")
                        .HasColumnType("uuid")
                        .HasColumnName("repo_id");

                    b.Property<decimal?>("RequireApprovalAboveUsd")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("require_approval_above_usd");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auto_dispatch_policies");

                    b.HasIndex("RepoId")
                        .HasDatabaseName("ix_auto_dispatch_policies_repo_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_auto_dispatch_policies_user_id");

                    b.HasIndex("OrgId", "Enabled")
                        .HasDatabaseName("ix_auto_dispatch_policies_org_id_enabled");

                    b.ToTable("auto_dispatch_policies", (string)null);
                });

            modelBuilder.Entity("Charter.Domain.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<double[]>("AlertThresholds")
                        .IsRequired()
                        .HasColumnType("double precision[]")
                        .HasColumnName("alert_thresholds");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("amount");

                    b.Property<decimal?>("ApprovalThreshold")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("approval_threshold");

                    b.Property<string>("Behaviour")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("behaviour");

                    b.PrimitiveCollection<string[]>("Categories")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("categories");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("period");

                    b.Property<DateTimeOffset?>("PeriodAnchor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_anchor");

                    b.Property<decimal>("ReservedAmount")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("reserved_amount");

                    b.Property<string>("Rollover")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rollover");

                    b.Property<decimal?>("RolloverCap")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("rollover_cap");

                    b.Property<string>("ScopeId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scope_id");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope_type");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_budgets");

                    b.HasIndex("OrgId", "ScopeType", "ScopeId")
                        .HasDatabaseName("ix_budgets_org_id_scope_type_scope_id");

                    b.ToTable("budgets", (string)null);
                });

            modelBuilder.Entity("Charter.Domain.ConceptLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Concept")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("concept");

                    b.Property<DateTimeOffset>("FirstExplainedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_explained_at");

                    b.Property<DateTimeOffset>("LastReferencedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_referenced_at");

                    b.Property<int>("TimesReferenced")
                        .HasColumnType("integer")
                        .HasColumnName("times_referenced");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_concept_ledger");

                    b.HasIndex("UserId", "Concept")
                        .IsUnique()
                        .HasDatabaseName("ux_concept_ledger_user_id_concept");

                    b.HasIndex("UserId", "LastReferencedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_concept_ledger_user_id_last_referenced_at");

                    b.ToTable("concept_ledger", (string)null);
                });

            modelBuilder.Entity("Charter.Domain.ConversationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid?>("ConfirmedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by");

                    b.Property<string>("ConfirmedContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("confirmed_content_hash");

                    b.Property<int>("FlagCount")
                        .HasColumnType("integer")
                        .HasColumnName("flag_count");

                    b.Property<string>("Flags")
                        .HasColumnType("jsonb")
                        .HasColumnName("flags");

                    b.Property<bool>("FlagsCleared")
                        .HasColumnType("boolean")
                        .HasColumnName("flags_cleared");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mode");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("Spec")
                        .HasColumnType("jsonb")
                        .HasColumnName("spec");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_conversations");

                    b.HasIndex("ConfirmedBy")
                        .HasDatabaseName("ix_conversations_confirmed_by");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("ix_conversations_request_id");

                    b.HasIndex("OrgId", "UpdatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_conversations_org_id_updated_at");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("Charter.Domain.ConversationTurnRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mode");

                    b.Property<int>("Seq")
                        .HasColumnType("integer")
                        .HasColumnName("seq");

                    b.HasKey("Id")
                        .HasName("pk_conversation_turns");

                    b.HasIndex("ConversationId", "Seq")
                        .IsUnique()
                        .HasDatabaseName("ux_conversation_turns_conversation_id_seq");

                    b.ToTable("conversation_turns", (string)null);
                });

            modelBuilder.Entity("Charter.Domain.CredentialGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExhaustedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exhausted_until");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("InvalidReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("invalid_reason");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<int?>("MaxSessionsPerDayFromOthers")
                        .HasColumnType("integer")
                        .HasColumnName("max_sessions_per_day_from_others");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<bool>("OverflowEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("overflow_enabled");

                    b.Property<DateTimeOffset?>("OverflowExhaustedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("overflow_exhausted_until");

                    b.Property<string>("OverflowStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("overflow_status");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<byte[]>("RefreshTokenEncrypted")
                        .HasColumnType("bytea")
                        .HasColumnName("refresh_token_encrypted");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<byte[]>("SecretEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_encrypted");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_credential_grants");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_credential_grants_owner_user_id");

                    b.HasIndex("OrgId", "Status", "Priority")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_credential_grants_org_id_status_priority");

                    b.ToTable("credential_grants", (string)null);
                });

            modelBuilder.Entity("Charter.Domain.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("provider");

                    b.Property<Guid>("ChangeRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("change_request_id");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_deployments");

                    b.HasIndex("ChangeRequestId", "ReportedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_deployments_change_request_id_reported_at");

                    b.ToTable("deployments", (string)null);
                });

            modelBuilder.Entity("Charter.Domain.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_events_created_at");

                    b.HasIndex("SessionId", "Seq")
                        .IsUnique()
                        .HasDatabaseName("ux_events_session_id_seq");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Charter.Domain.Identity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_user_id");

                    b.Property<string>("SecretHash")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("secret_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_identities");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_identities_user_id");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_identities_provider_provider_user_id");

                    b.ToTable("identities", (string)null);
                });

            modelBuilder.Entity("Charter.Domain.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("claimed_by");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.PrimitiveCollection<string[]>("RequiredCapabilities")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("required_capabilities");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("ClaimedBy")
                        .HasDatabaseName("ix_jobs_claimed_by")
                        .HasFilter("status = 'claimed'");

                    b.HasIndex("LeaseExpiresAt")
                        .HasDatabaseName("ix_jobs_lease_expires_at")
                        .HasFilter("status = 'claimed'");

                    b.HasIndex("RequiredCapabilities")
                        .HasDatabaseName("ix_jobs_required_capabilities");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("RequiredCapabilities"), "gin");

                    b.HasIndex("Status", "Priority", "AvailableAt")
                        .IsDescending(false, true, false)
                        .HasDatabaseName("ix_jobs_claimable")
                        .HasFilter("status = 'pending'");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("Charter.Domain.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<Guid[]>("BudgetIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("budget_ids");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CredentialGrantId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_grant_id");

                    b.Property<decimal>("ImputedUsd")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("imputed_usd");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<decimal>("QuotaSessions")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("quota_sessions");

                    b.Property<DateTimeOffset?>("ReservedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reserved_until");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset?>("SettledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("settled_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<decimal>("Usd")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("usd");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_ledger_entries");

                    b.HasIndex("BudgetIds")
                        .HasDatabaseName("ix_ledger_entries_budget_ids");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("BudgetIds"), "gin");

                    b.HasIndex("CredentialGrantId")
                        .HasDatabaseName("ix_ledger_entries_credential_grant_id");

                    b.HasIndex("ReservedUntil")
                        .HasDatabaseName("ix_ledger_entries_reserved_until")
                        .HasFilter("state = 'reserved'");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_ledger_entries_session_id");

                    b.HasIndex("OrgId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_ledger_entries_org_id_created_at");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_ledger_entries_user_id_created_at");

                    b.ToTable("ledger_entries", (string)null);
                });

            modelBuilder.Entity("Charter.Domain.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("Capabilities")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("capabilities");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.PrimitiveCollection<string[]>("Roles")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("roles");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_members");

                    b.HasIndex("Roles")
                        .HasDatabaseName("ix_members_roles");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Roles"), "gin");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_members_user_id");

                    b.HasIndex("OrgId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_members_org_id_user_id");

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("Charter.Domain.Milestone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnnotationMd")
                        .HasColumnType("text")
                        .HasColumnName("annotation_md");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("pk_milestones");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ux_milestones_event_id");

                    b.HasIndex("SessionId", "CreatedAt")
                        .HasDatabaseName("ix_milestones_session_id_created_at");

                    b.ToTable("milestones", (string)null);
                });

            modelBuilder.Entity("Charter.Domain.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Charter.Domain.ChangeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorLogin")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("author_login");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HeadBranch")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("head_branch");

                    b.Property<string>("HeadSha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("head_sha");

                    b.Property<bool>("IsStale")
                        .HasColumnType("boolean")
                        .HasColumnName("is_stale");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_change_requests");

                    b.HasIndex("HeadSha")
                        .HasDatabaseName("ix_change_requests_head_sha");

                    b.HasIndex("SessionId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ux_change_requests_session_id_number");

                    b.ToTable("change_requests", (string)null);
                });

            modelBuilder.Entity("Charter.Domain.Recap", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BodyMd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_md");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("cost_usd");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("RiskItems")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("risk_items");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("pk_recaps");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasDatabaseName("ux_recaps_session_id");

                    b.ToTable("recaps", (string)null);
                });

            modelBuilder.Entity("Charter.Domain.Repo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseBranch")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("base_branch");

                    b.Property<string>("CharterConfigSnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("charter_config_snapshot");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<long>("GithubInstallationId")
                        .HasColumnType("bigint")
                        .HasColumnName("github_installation_id");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("PrimerMd")
                        .HasColumnType("text")
                        .HasColumnName("primer_md");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_repos");

                    b.HasIndex("GithubInstallationId")
                        .HasDatabaseName("ix_repos_github_installation_id");

                    b.HasIndex("OrgId", "FullName")
                        .IsUnique()
                        .HasDatabaseName("ux_repos_org_id_full_name");

                    b.ToTable("repos", (string)null);
                });

            modelBuilder.Entity("Charter.Domain.RepoScope", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CanRequest")
                        .HasColumnType("boolean")
                        .HasColumnName("can_request");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<Guid>("RepoId")
                        .HasColumnType("uuid")
                        .HasColumnName("repo_id");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_repo_scopes");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_repo_scopes_member_id");

                    b.HasIndex("RepoId", "MemberId")
                        .IsUnique()
                        .HasDatabaseName("ux_repo_scopes_repo_id_member_id")
                        .HasFilter("member_id IS NOT NULL");

                    b.HasIndex("RepoId", "Role")
                        .IsUnique()
                        .HasDatabaseName("ux_repo_scopes_repo_id_role")
                        .HasFilter("role IS NOT NULL");

                    b.ToTable("repo_scopes", null, t =>
                        {
                            t.HasCheckConstraint("ck_repo_scopes_member_xor_role", "(member_id IS NULL) <> (role IS NULL)");
                        });
                });

            modelBuilder.Entity("Charter.Domain.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<Guid>("RepoId")
                        .HasColumnType("uuid")
                        .HasColumnName("repo_id");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TemplateId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("template_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_requests");

                    b.HasIndex("OrgId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_requests_org_id_created_at");

                    b.HasIndex("RepoId", "Status")
                        .HasDatabaseName("ix_requests_repo_id_status");

                    b.HasIndex("RequesterId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_requests_requester_id_created_at");

                    b.ToTable("requests", (string)null);
                });

            modelBuilder.Entity("Charter.Domain.RequestFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("note");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("SubmittedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verdict");

                    b.HasKey("Id")
                        .HasName("pk_request_feedback");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_request_feedback_session_id");

                    b.HasIndex("SubmittedBy")
                        .HasDatabaseName("ix_request_feedback_submitted_by");

                    b.HasIndex("RequestId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_request_feedback_request_id_created_at");

                    b.ToTable("request_feedback", (string)null);
                });

            modelBuilder.Entity("Charter.Domain.RunnerAgent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentVersion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("agent_version");

                    b.Property<string>("Arch")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("arch");

                    b.PrimitiveCollection<string[]>("Capabilities")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("capabilities");

                    b.Property<string>("CapabilitiesHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("capabilities_hash");

                    b.Property<DateTimeOffset?>("CapabilitiesProbedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("capabilities_probed_at");

                    b.Property<int>("Concurrency")
                        .HasColumnType("integer")
                        .HasColumnName("concurrency");

                    b.Property<int>("CpuCount")
                        .HasColumnType("integer")
                        .HasColumnName("cpu_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CredentialHash")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("credential_hash");

                    b.Property<string>("Hostname")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hostname");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Os")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("os");

                    b.Property<DateTimeOffset?>("PairedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paired_at");

                    b.Property<DateTimeOffset?>("PairingTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pairing_token_expires_at");

                    b.Property<string>("PairingTokenHash")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("pairing_token_hash");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("integer")
                        .HasColumnName("protocol_version");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("revoked_reason");

                    b.Property<string>("Rid")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("rid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_runner_agents");

                    b.HasIndex("Capabilities")
                        .HasDatabaseName("ix_runner_agents_capabilities");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Capabilities"), "gin");

                    b.HasIndex("PairingTokenExpiresAt")
                        .HasDatabaseName("ix_runner_agents_pairing_token_expires_at")
                        .HasFilter("pairing_token_hash IS NOT NULL");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_runner_agents_status");

                    b.HasIndex("OrgId", "Name")
                        .HasDatabaseName("ix_runner_agents_org_id_name");

                    b.ToTable("runner_agents", (string)null);
                });

            modelBuilder.Entity("Charter.Domain.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentModel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("agent_model");

                    b.Property<bool>("AutoDispatched")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_dispatched");

                    b.Property<string>("BaseCommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("base_commit_sha");

                    b.Property<DateTimeOffset?>("CancelRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancel_requested_at");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("cost_usd");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("Runner")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("runner");

                    b.Property<Guid>("SpecId")
                        .HasColumnType("uuid")
                        .HasColumnName("spec_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("SpecId")
                        .HasDatabaseName("ix_sessions_spec_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_sessions_status_created_at");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Charter.Domain.Spec", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AcceptanceCriteria")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("acceptance_criteria");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<string>("BodyMd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_md");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("OpenQuestions")
                        .HasColumnType("jsonb")
                        .HasColumnName("open_questions");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("Risks")
                        .HasColumnType("jsonb")
                        .HasColumnName("risks");

                    b.Property<string>("Scope")
                        .HasColumnType("jsonb")
                        .HasColumnName("scope");

                    b.Property<string>("TechnicalApproach")
                        .HasColumnType("text")
                        .HasColumnName("technical_approach");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_specs");

                    b.HasIndex("ApprovedBy")
                        .HasDatabaseName("ix_specs_approved_by");

                    b.HasIndex("RequestId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_specs_request_id_version");

                    b.ToTable("specs", (string)null);
                });

            modelBuilder.Entity("Charter.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Pane")
                        .HasColumnType("text")
                        .HasColumnName("pane");

                    b.Property<DateTimeOffset?>("RequesterOnboardingCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requester_onboarding_completed_at");

                    b.Property<string>("TeachingLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("teaching_level");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("theme");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Charter.Domain.VerificationArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("audience");

                    b.Property<string>("ConnectString")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("connect_string");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FileRef")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_ref");

                    b.Property<string>("InstructionsMd")
                        .HasColumnType("text")
                        .HasColumnName("instructions_md");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_verification_artifacts");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_verification_artifacts_expires_at")
                        .HasFilter("expires_at IS NOT NULL");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_verification_artifacts_session_id");

                    b.ToTable("verification_artifacts", (string)null);
                });

            modelBuilder.Entity("Charter.Domain.Walkthrough", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BodyMd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_md");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("cost_usd");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("pk_walkthroughs");

                    b.HasIndex("SessionId", "Level")
                        .IsUnique()
                        .HasDatabaseName("ux_walkthroughs_session_id_level");

                    b.ToTable("walkthroughs", (string)null);
                });

            modelBuilder.Entity("Charter.Domain.AuditLog", b =>
                {
                    b.HasOne("Charter.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_logs_users_actor_user_id");

                    b.HasOne("Charter.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audit_logs_organizations_org_id");
                });

            modelBuilder.Entity("Charter.Domain.AutoDispatchPolicy", b =>
                {
                    b.HasOne("Charter.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auto_dispatch_policies_organizations_org_id");

                    b.HasOne("Charter.Domain.Repo", null)
                        .WithMany()
                        .HasForeignKey("RepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_auto_dispatch_policies_repos_repo_id");

                    b.HasOne("Charter.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_auto_dispatch_policies_users_user_id");
                });

            modelBuilder.Entity("Charter.Domain.Budget", b =>
                {
                    b.HasOne("Charter.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budgets_organizations_org_id");
                });

            modelBuilder.Entity("Charter.Domain.ConceptLedger", b =>
                {
                    b.HasOne("Charter.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_concept_ledger_users_user_id");
                });

            modelBuilder.Entity("Charter.Domain.ConversationRecord", b =>
                {
                    b.HasOne("Charter.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("ConfirmedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_conversations_users_confirmed_by");

                    b.HasOne("Charter.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversations_organizations_org_id");

                    b.HasOne("Charter.Domain.Request", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_conversations_requests_request_id");
                });

            modelBuilder.Entity("Charter.Domain.ConversationTurnRecord", b =>
                {
                    b.HasOne("Charter.Domain.ConversationRecord", null)
                        .WithMany("Turns")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversation_turns_conversations_conversation_id");
                });

            modelBuilder.Entity("Charter.Domain.CredentialGrant", b =>
                {
                    b.HasOne("Charter.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_credential_grants_organizations_org_id");

                    b.HasOne("Charter.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_credential_grants_users_owner_user_id");
                });

            modelBuilder.Entity("Charter.Domain.Deployment", b =>
                {
                    b.HasOne("Charter.Domain.ChangeRequest", null)
                        .WithMany()
                        .HasForeignKey("ChangeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deployments_change_requests_change_request_id");
                });

            modelBuilder.Entity("Charter.Domain.Event", b =>
                {
                    b.HasOne("Charter.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_events_sessions_session_id");
                });

            modelBuilder.Entity("Charter.Domain.Identity", b =>
                {
                    b.HasOne("Charter.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_identities_users_user_id");
                });

            modelBuilder.Entity("Charter.Domain.LedgerEntry", b =>
                {
                    b.HasOne("Charter.Domain.CredentialGrant", null)
                        .WithMany()
                        .HasForeignKey("CredentialGrantId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_ledger_entries_credential_grants_credential_grant_id");

                    b.HasOne("Charter.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ledger_entries_organizations_org_id");

                    b.HasOne("Charter.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_ledger_entries_sessions_session_id");

                    b.HasOne("Charter.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ledger_entries_users_user_id");
                });

            modelBuilder.Entity("Charter.Domain.Member", b =>
                {
                    b.HasOne("Charter.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_members_organizations_org_id");

                    b.HasOne("Charter.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_members_users_user_id");
                });

            modelBuilder.Entity("Charter.Domain.Milestone", b =>
                {
                    b.HasOne("Charter.Domain.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_milestones_events_event_id");

                    b.HasOne("Charter.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_milestones_sessions_session_id");
                });

            modelBuilder.Entity("Charter.Domain.ChangeRequest", b =>
                {
                    b.HasOne("Charter.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_change_requests_sessions_session_id");
                });

            modelBuilder.Entity("Charter.Domain.Recap", b =>
                {
                    b.HasOne("Charter.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recaps_sessions_session_id");
                });

            modelBuilder.Entity("Charter.Domain.Repo", b =>
                {
                    b.HasOne("Charter.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_repos_organizations_org_id");
                });

            modelBuilder.Entity("Charter.Domain.RepoScope", b =>
                {
                    b.HasOne("Charter.Domain.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_repo_scopes_members_member_id");

                    b.HasOne("Charter.Domain.Repo", null)
                        .WithMany()
                        .HasForeignKey("RepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_repo_scopes_repos_repo_id");
                });

            modelBuilder.Entity("Charter.Domain.Request", b =>
                {
                    b.HasOne("Charter.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_requests_organizations_org_id");

                    b.HasOne("Charter.Domain.Repo", null)
                        .WithMany()
                        .HasForeignKey("RepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_requests_repos_repo_id");

                    b.HasOne("Charter.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_requests_users_requester_id");
                });

            modelBuilder.Entity("Charter.Domain.RequestFeedback", b =>
                {
                    b.HasOne("Charter.Domain.Request", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_request_feedback_requests_request_id");

                    b.HasOne("Charter.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_request_feedback_sessions_session_id");

                    b.HasOne("Charter.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("SubmittedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_request_feedback_users_submitted_by");
                });

            modelBuilder.Entity("Charter.Domain.RunnerAgent", b =>
                {
                    b.HasOne("Charter.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_runner_agents_organizations_org_id");
                });

            modelBuilder.Entity("Charter.Domain.Session", b =>
                {
                    b.HasOne("Charter.Domain.Spec", null)
                        .WithMany()
                        .HasForeignKey("SpecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_specs_spec_id");
                });

            modelBuilder.Entity("Charter.Domain.Spec", b =>
                {
                    b.HasOne("Charter.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_specs_users_approved_by");

                    b.HasOne("Charter.Domain.Request", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_specs_requests_request_id");
                });

            modelBuilder.Entity("Charter.Domain.VerificationArtifact", b =>
                {
                    b.HasOne("Charter.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verification_artifacts_sessions_session_id");
                });

            modelBuilder.Entity("Charter.Domain.Walkthrough", b =>
                {
                    b.HasOne("Charter.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_walkthroughs_sessions_session_id");
                });

            modelBuilder.Entity("Charter.Domain.ConversationRecord", b =>
                {
                    b.Navigation("Turns");
                });
#pragma warning restore 612, 618
        }
    }
}
